apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_f2c534786301
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: rootpassword
          resources:
            limits:
              memory: 1Gi
          readinessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "mongo --eval 'db.adminCommand({ping: 1})'"
            initialDelaySeconds: 30
            timeoutSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: ClusterIP
  clusterIP: None # Headless
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017